### ISSUE TITLE
Remove server

### ISSUE THREAD

**Issue by jenniferabowd** [jenniferkaplannyc/jest_react_redux_node_webpack_complex_example#10]
This example is very convoluted. I think we can just remove the server to simplify it.

**Comment by brandonmcconnell** [comment]
@jenniferabowd In removing the server, will we just be hard-coding those values from `` into the template `` itself?

If that's all, please assign me to this, and I'll take care of that. Otherwise, would you mind clarifying the work required here? Thanks!

**Comment by jenniferabowd** [comment]
Yeah, I’m good with them being hardcoded! Thank you so much for your help!

**Comment by brandonmcconnell** [comment]
@jenniferabowd Sure thing! I'll get on these in the next day or two. Flying tomorrow 🛩️

**Comment by jenniferabowd** [comment]
Safe travels!

**Comment by jenniferabowd** [comment]
Hi, I wanted to check-in on this. If you don't think you are going to get to it, I can unassign you. Also, no rush if you are working on it or got busy with travel!

**Comment by brandonmcconnell** [comment]
@jenniferabowd Hey! Yeah, I did get pretty busy with my travels, and I'm not sure when I'll have time next week to circle back to this.

I did make some major headway, so what may be best is if I open a draft PR with the changes I've made so far, so someone can pick up where I left off. Hopefully shouldn't be too much more work involved.

**Comment by jenniferabowd** [comment]
Oh awesome! That's a great idea! Thanks for helping out with this!

**Comment by brandonmcconnell** [comment]
@jenniferabowd If you wouldn't mind leaving this assigned to me, I should be able to dive in more next week. Looks like webpack 5 was a pit of a dependency here, so IK just went ahead and did that upgrade, but because the two branches are intertwined/stacked, we'll need to push both simultaneously.

**Comment by jenniferabowd** [comment]
Cool! I think what would be most helpful is having one folder for Webpack 2 and another folder for Webpack 5. I believe the solutions for those versions of Webpack is pretty different, so I figured having both in this repo would be helpful. Thank you so much for all of your help on this!

**Comment by brandonmcconnell** [comment]
@jenniferabowd Looks like that should be possible using version aliasing, mentioned [here](https://stackoverflow.com/a/57817745/3824249).

Considering the lift that was involved in upgrading webpack 2 → 5, I can only imagine this might be a pretty sizable lift too, so it might help to merge everything open now first and then go back and re-add examples for webpack v2.

**Comment by brandonmcconnell** [comment]
@jenniferabowd If you haven't already seen my comment re the intended merge order, please read that first, [here](https://github.com/jenniferabowd/jest_webpack_example/pull/19#issuecomment-1279577683).

Could you also please assign me to all those tickets before merging to ensure I'm attributed to their merge?

**Comment by jenniferabowd** [comment]
Sure! Let me review this code. Would you be okay if I go into your PR and do what I meant with the 2 webpack versions? What I had in mind shouldn't take too long.

**Comment by brandonmcconnell** [comment]
@jenniferabowd Of course! Make any changes as you see fit
