### ISSUE TITLE
jest - console.error node_modules/fbjs/lib/warning.js:33

### ISSUE THREAD

**Issue by speaud** [jenniferkaplannyc/jest_react_redux_node_webpack_complex_example#2]
The error below is returned when running jest

 PASS  reactTests/tests/teamAmerica.test.js
  ✓ test to see if the team renders correctly (22ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   1 passed, 1 total
Time:        1.451s
Ran all test suites.
  console.error node_modules/fbjs/lib/warning.js:33
    Warning: Each child in an array or iterator should have a unique "key" prop.
    
    Check the render method of `TeamAmerica`. See https://fb.me/react-warning-keys for more information.
        in div (created by TeamAmerica)
        in TeamAmerica

**Comment by jenniferabowd** [comment]
@speaud Thank you for this issue ticket. To be honest, this is a warning message. I will fix it when I have some time in the future as right now my plate is pretty full. However, until then you are more than welcome to submit a pull request.

**Comment by speaud** [comment]
@jenniferkaplannyc I do not believe this issue had been resolved. 

I've submitted a PR as you've requested which contains the fix for this pending issue.

**Comment by jenniferabowd** [comment]
Thank you! You fixed the issue! I really appreciate it! I'm working 3 jobs so I don't have much time right now.

**Comment by speaud** [comment]
No worries, I completely get it. Let me know if you need the PR for the .gitignore, it'll only take a second

**Comment by speaud** [comment]
I confirm this issue has been resolved. Thanks!

**Comment by jenniferabowd** [comment]
I can do the PR! Thank you!
