### ISSUE TITLE
Add Webpack 5 version

### ISSUE THREAD

**Issue by jenniferabowd** [jenniferkaplannyc/jest_react_redux_node_webpack_complex_example#8]
Hi, this example has become a bit stale. I'm hoping someone can help modernize this example to help others during Hacktoberfest. If it doesn't happen, that is okay, but maybe this can be a good chance for someone to participate. I'm making several tickets to help break this up into chunks. I'm happy to help people, but I don't have much time to rewrite this code.

Can someone upgrade Webpack to the current version please?

**Comment by jenniferabowd** [comment]
Actually, I think having this verison in webpack 2 has value. So maybe we can restructure this repo to have two folders, one for webpack 2 and one for webpack 5?

**Comment by NazimFilzer** [comment]
Hey Can i take a Look?

**Comment by jenniferabowd** [comment]
Yup! Do you want me to assign it to you or not yet?

**Comment by NazimFilzer** [comment]
Please do... I will give it a try

**Comment by brandonmcconnell** [comment]
@jenniferabowd Could you assign me? This ended up being a prerequisite for both upgrading Jest and removing the server, so I've already done this.
