### ISSUE TITLE
Remove redux

### ISSUE THREAD

**Issue by jenniferabowd** [jenniferkaplannyc/jest_react_redux_node_webpack_complex_example#9]
This example is very convoluted due to some decisions made several years ago. I think it would be great to just remove redux. I also don't think we need the server, but that can be a separate ticket.

**Comment by brandonmcconnell** [comment]
@jenniferabowd I've updated Redux to its latest version in #13 but would you prefer it removed altogether?

If so, I can take care of that. Do you know where it's currently being used if at all, or if this will just be a plain removal, with no other changes needed?

**Comment by jenniferabowd** [comment]
This is being used to get the data. I would prefer it be removed all together. This will involve deleting several files and refactoring at least 2 files.
